//
// File generated by /home/salvatore/root/bin/rootcint at Tue Apr 14 15:18:13 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictEvent
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "dictEvent.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void vecLor_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_vecLor(void *p = 0);
   static void *newArray_vecLor(Long_t size, void *p);
   static void delete_vecLor(void *p);
   static void deleteArray_vecLor(void *p);
   static void destruct_vecLor(void *p);
   static void streamer_vecLor(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::vecLor*)
   {
      ::vecLor *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::vecLor >(0);
      static ::ROOT::TGenericClassInfo 
         instance("vecLor", ::vecLor::Class_Version(), "./vecLor.h", 13,
                  typeid(::vecLor), ::ROOT::DefineBehavior(ptr, ptr),
                  &::vecLor::Dictionary, isa_proxy, 0,
                  sizeof(::vecLor) );
      instance.SetNew(&new_vecLor);
      instance.SetNewArray(&newArray_vecLor);
      instance.SetDelete(&delete_vecLor);
      instance.SetDeleteArray(&deleteArray_vecLor);
      instance.SetDestructor(&destruct_vecLor);
      instance.SetStreamerFunc(&streamer_vecLor);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::vecLor*)
   {
      return GenerateInitInstanceLocal((::vecLor*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::vecLor*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void event_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_event(void *p = 0);
   static void *newArray_event(Long_t size, void *p);
   static void delete_event(void *p);
   static void deleteArray_event(void *p);
   static void destruct_event(void *p);
   static void streamer_event(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::event*)
   {
      ::event *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::event >(0);
      static ::ROOT::TGenericClassInfo 
         instance("event", ::event::Class_Version(), "./event.h", 15,
                  typeid(::event), ::ROOT::DefineBehavior(ptr, ptr),
                  &::event::Dictionary, isa_proxy, 0,
                  sizeof(::event) );
      instance.SetNew(&new_event);
      instance.SetNewArray(&newArray_event);
      instance.SetDelete(&delete_event);
      instance.SetDeleteArray(&deleteArray_event);
      instance.SetDestructor(&destruct_event);
      instance.SetStreamerFunc(&streamer_event);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::event*)
   {
      return GenerateInitInstanceLocal((::event*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::event*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr vecLor::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *vecLor::Class_Name()
{
   return "vecLor";
}

//______________________________________________________________________________
const char *vecLor::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::vecLor*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int vecLor::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::vecLor*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void vecLor::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::vecLor*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *vecLor::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::vecLor*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr event::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *event::Class_Name()
{
   return "event";
}

//______________________________________________________________________________
const char *event::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::event*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int event::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::event*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void event::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::event*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *event::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::event*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void vecLor::Streamer(TBuffer &R__b)
{
   // Stream an object of class vecLor.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> p0;
      R__b >> p1;
      R__b >> p2;
      R__b >> p3;
      R__b.CheckByteCount(R__s, R__c, vecLor::IsA());
   } else {
      R__c = R__b.WriteVersion(vecLor::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << p0;
      R__b << p1;
      R__b << p2;
      R__b << p3;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void vecLor::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class vecLor.
      TClass *R__cl = ::vecLor::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p0", &p0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p1", &p1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p2", &p2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "p3", &p3);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vecLor(void *p) {
      return  p ? new(p) ::vecLor : new ::vecLor;
   }
   static void *newArray_vecLor(Long_t nElements, void *p) {
      return p ? new(p) ::vecLor[nElements] : new ::vecLor[nElements];
   }
   // Wrapper around operator delete
   static void delete_vecLor(void *p) {
      delete ((::vecLor*)p);
   }
   static void deleteArray_vecLor(void *p) {
      delete [] ((::vecLor*)p);
   }
   static void destruct_vecLor(void *p) {
      typedef ::vecLor current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_vecLor(TBuffer &buf, void *obj) {
      ((::vecLor*)obj)->::vecLor::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::vecLor

//______________________________________________________________________________
void event::Streamer(TBuffer &R__b)
{
   // Stream an object of class event.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> eventNumber;
      R__b >> vecLorArray;
      R__b.CheckByteCount(R__s, R__c, event::IsA());
   } else {
      R__c = R__b.WriteVersion(event::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << eventNumber;
      R__b << vecLorArray;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void event::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class event.
      TClass *R__cl = ::event::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "eventNumber", &eventNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*vecLorArray", &vecLorArray);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_event(void *p) {
      return  p ? new(p) ::event : new ::event;
   }
   static void *newArray_event(Long_t nElements, void *p) {
      return p ? new(p) ::event[nElements] : new ::event[nElements];
   }
   // Wrapper around operator delete
   static void delete_event(void *p) {
      delete ((::event*)p);
   }
   static void deleteArray_event(void *p) {
      delete [] ((::event*)p);
   }
   static void destruct_event(void *p) {
      typedef ::event current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_event(TBuffer &buf, void *obj) {
      ((::event*)obj)->::event::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::event

/********************************************************
* dictEvent.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtabledictEvent();

extern "C" void G__set_cpp_environmentdictEvent() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("vecLor.h");
  G__add_compiledheader("event.h");
  G__cpp_reset_tagtabledictEvent();
}
#include <new>
extern "C" int G__cpp_dllrevdictEvent() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* vecLor */
static int G__dictEvent_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vecLor* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vecLor[n];
     } else {
       p = new((void*) gvp) vecLor[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new vecLor;
     } else {
       p = new((void*) gvp) vecLor;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_vecLor));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vecLor* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 4
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new vecLor(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3]));
   } else {
     p = new((void*) gvp) vecLor(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_vecLor));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vecLor* pobj;
         vecLor xobj = ((vecLor*) G__getstructoffset())->operator+=(*(vecLor*) libp->para[0].ref);
         pobj = new vecLor(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         vecLor* pobj;
         vecLor xobj = ((vecLor*) G__getstructoffset())->operator+(*(vecLor*) libp->para[0].ref);
         pobj = new vecLor(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vecLor*) G__getstructoffset())->SetP0((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vecLor*) G__getstructoffset())->SetP1((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vecLor*) G__getstructoffset())->SetP2((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vecLor*) G__getstructoffset())->SetP3((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vecLor*) G__getstructoffset())->GetP0());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vecLor*) G__getstructoffset())->GetP1());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vecLor*) G__getstructoffset())->GetP2());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((vecLor*) G__getstructoffset())->GetP3());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vecLor*) G__getstructoffset())->boost((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vecLor*) G__getstructoffset())->randomDirection((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vecLor*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((const vecLor*) G__getstructoffset())->Length());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) vecLor::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vecLor::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) vecLor::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      vecLor::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((vecLor*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vecLor::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) vecLor::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) vecLor::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_168_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) vecLor::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dictEvent_168_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   vecLor* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new vecLor(*(vecLor*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_vecLor));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef vecLor G__TvecLor;
static int G__dictEvent_168_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (vecLor*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((vecLor*) (soff+(sizeof(vecLor)*i)))->~G__TvecLor();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (vecLor*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((vecLor*) (soff))->~G__TvecLor();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dictEvent_168_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   vecLor* dest = (vecLor*) G__getstructoffset();
   *dest = *(vecLor*) libp->para[0].ref;
   const vecLor& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* event */
static int G__dictEvent_192_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   event* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new event[n];
     } else {
       p = new((void*) gvp) event[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new event;
     } else {
       p = new((void*) gvp) event;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_event));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   event* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new event((int) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) event((int) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_event));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->SetEventNumber((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->AddvecLor((vecLor*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->AddvecLor((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((event*) G__getstructoffset())->GetEventNumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((event*) G__getstructoffset())->GetNumberOfTracks());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((event*) G__getstructoffset())->GetTrack((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->PrintTracks();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->DoSort();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) event::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) event::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) event::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      event::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((event*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) event::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) event::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) event::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__dictEvent_192_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) event::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__dictEvent_192_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   event* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new event(*(event*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__dictEventLN_event));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef event G__Tevent;
static int G__dictEvent_192_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (event*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((event*) (soff+(sizeof(event)*i)))->~G__Tevent();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (event*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((event*) (soff))->~G__Tevent();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__dictEvent_192_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   event* dest = (event*) G__getstructoffset();
   *dest = *(event*) libp->para[0].ref;
   const event& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* vecLor */

/* event */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncdictEvent {
 public:
  G__Sizep2memfuncdictEvent(): p(&G__Sizep2memfuncdictEvent::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncdictEvent::*p)();
};

size_t G__get_sizep2memfuncdictEvent()
{
  G__Sizep2memfuncdictEvent a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancedictEvent() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictEventLN_vecLor))) {
     vecLor *G__Lderived;
     G__Lderived=(vecLor*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictEventLN_vecLor),G__get_linked_tagnum(&G__dictEventLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__dictEventLN_event))) {
     event *G__Lderived;
     G__Lderived=(event*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__dictEventLN_event),G__get_linked_tagnum(&G__dictEventLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetabledictEvent() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* vecLor */
static void G__setup_memvarvecLor(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictEventLN_vecLor));
   { vecLor *p; p=(vecLor*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"p0=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"p1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"p2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,2,"p3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictEventLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* event */
static void G__setup_memvarevent(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__dictEventLN_event));
   { event *p; p=(event*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,2,"eventNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictEventLN_TObjArray),-1,-1,2,"vecLorArray=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__dictEventLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvardictEvent() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncvecLor(void) {
   /* vecLor */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictEventLN_vecLor));
   G__memfunc_setup("vecLor",619,G__dictEvent_168_0_1, 105, G__get_linked_tagnum(&G__dictEventLN_vecLor), -1, 0, 0, 1, 1, 0, "", "default", (void*) NULL, 0);
   G__memfunc_setup("vecLor",619,G__dictEvent_168_0_2, 105, G__get_linked_tagnum(&G__dictEventLN_vecLor), -1, 0, 4, 1, 1, 0, 
"d - - 0 - mp0 d - - 0 - mp1 "
"d - - 0 - mp2 d - - 0 - mp3", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+=",980,G__dictEvent_168_0_3, 117, G__get_linked_tagnum(&G__dictEventLN_vecLor), -1, 0, 1, 1, 1, 0, "u 'vecLor' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("operator+",919,G__dictEvent_168_0_4, 117, G__get_linked_tagnum(&G__dictEventLN_vecLor), -1, 0, 1, 1, 1, 0, "u 'vecLor' - 1 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetP0",428,G__dictEvent_168_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - mp0", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetP1",429,G__dictEvent_168_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - mp1", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetP2",430,G__dictEvent_168_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - mp2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetP3",431,G__dictEvent_168_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - mp3", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetP0",416,G__dictEvent_168_0_9, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetP1",417,G__dictEvent_168_0_10, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetP2",418,G__dictEvent_168_0_11, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetP3",419,G__dictEvent_168_0_12, 100, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("boost",551,G__dictEvent_168_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - gamma", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("randomDirection",1570,G__dictEvent_168_0_14, 121, -1, -1, 0, 3, 1, 1, 0, 
"d - - 0 - p1 d - - 0 - theta "
"d - - 0 - phi", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__dictEvent_168_0_15, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Length",610,G__dictEvent_168_0_16, 100, -1, -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsSortable",1016,(G__InterfaceMethod) NULL,103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Compare",711,(G__InterfaceMethod) NULL,105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 8, "U 'TObject' - 10 - obj", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Class",502,G__dictEvent_168_0_19, 85, G__get_linked_tagnum(&G__dictEventLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&vecLor::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dictEvent_168_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vecLor::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dictEvent_168_0_21, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&vecLor::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dictEvent_168_0_22, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&vecLor::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictEventLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dictEvent_168_0_26, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dictEvent_168_0_27, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vecLor::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dictEvent_168_0_28, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&vecLor::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dictEvent_168_0_29, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&vecLor::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dictEvent_168_0_30, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&vecLor::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("vecLor", 619, G__dictEvent_168_0_31, (int) ('i'), G__get_linked_tagnum(&G__dictEventLN_vecLor), -1, 0, 1, 1, 1, 0, "u 'vecLor' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~vecLor", 745, G__dictEvent_168_0_32, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dictEvent_168_0_33, (int) ('u'), G__get_linked_tagnum(&G__dictEventLN_vecLor), -1, 1, 1, 1, 1, 0, "u 'vecLor' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncevent(void) {
   /* event */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__dictEventLN_event));
   G__memfunc_setup("event",546,G__dictEvent_192_0_1, 105, G__get_linked_tagnum(&G__dictEventLN_event), -1, 0, 0, 1, 1, 0, "", "default", (void*) NULL, 0);
   G__memfunc_setup("event",546,G__dictEvent_192_0_2, 105, G__get_linked_tagnum(&G__dictEventLN_event), -1, 0, 1, 1, 1, 0, "i - - 0 - nEv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEventNumber",1431,G__dictEvent_192_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - nEv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddvecLor",884,G__dictEvent_192_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "U 'vecLor' - 0 - mv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddvecLor",884,G__dictEvent_192_0_5, 121, -1, -1, 0, 4, 1, 1, 0, 
"d - - 0 - mp0 d - - 0 - mp1 "
"d - - 0 - mp2 d - - 0 - mp3", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEventNumber",1419,G__dictEvent_192_0_6, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNumberOfTracks",1702,G__dictEvent_192_0_7, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTrack",789,G__dictEvent_192_0_8, 85, G__get_linked_tagnum(&G__dictEventLN_vecLor), -1, 0, 1, 1, 1, 0, "i - - 0 - nT", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__dictEvent_192_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintTracks",1141,G__dictEvent_192_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSort",603,G__dictEvent_192_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__dictEvent_192_0_12, 85, G__get_linked_tagnum(&G__dictEventLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&event::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__dictEvent_192_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&event::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__dictEvent_192_0_14, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&event::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__dictEvent_192_0_15, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&event::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__dictEventLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__dictEvent_192_0_19, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__dictEvent_192_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&event::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__dictEvent_192_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&event::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__dictEvent_192_0_22, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&event::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__dictEvent_192_0_23, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&event::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("event", 546, G__dictEvent_192_0_24, (int) ('i'), G__get_linked_tagnum(&G__dictEventLN_event), -1, 0, 1, 1, 1, 0, "u 'event' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~event", 672, G__dictEvent_192_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__dictEvent_192_0_26, (int) ('u'), G__get_linked_tagnum(&G__dictEventLN_event), -1, 1, 1, 1, 1, 0, "u 'event' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncdictEvent() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaldictEvent() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcdictEvent() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__dictEventLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__dictEventLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__dictEventLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__dictEventLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictEventLN_TObjArray = { "TObjArray" , 99 , -1 };
G__linked_taginfo G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__dictEventLN_vecLor = { "vecLor" , 99 , -1 };
G__linked_taginfo G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__dictEventLN_event = { "event" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtabledictEvent() {
  G__dictEventLN_TClass.tagnum = -1 ;
  G__dictEventLN_TBuffer.tagnum = -1 ;
  G__dictEventLN_TMemberInspector.tagnum = -1 ;
  G__dictEventLN_TObject.tagnum = -1 ;
  G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictEventLN_TObjArray.tagnum = -1 ;
  G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__dictEventLN_vecLor.tagnum = -1 ;
  G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__dictEventLN_event.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtabledictEvent() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__dictEventLN_TClass);
   G__get_linked_tagnum_fwd(&G__dictEventLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__dictEventLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__dictEventLN_TObject);
   G__get_linked_tagnum_fwd(&G__dictEventLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__dictEventLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__dictEventLN_TObjArray);
   G__get_linked_tagnum_fwd(&G__dictEventLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__dictEventLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictEventLN_vecLor),sizeof(vecLor),-1,62720,(char*)NULL,G__setup_memvarvecLor,G__setup_memfuncvecLor);
   G__get_linked_tagnum_fwd(&G__dictEventLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__dictEventLN_event),sizeof(event),-1,62720,(char*)NULL,G__setup_memvarevent,G__setup_memfuncevent);
}
extern "C" void G__cpp_setupdictEvent(void) {
  G__check_setup_version(30051515,"G__cpp_setupdictEvent()");
  G__set_cpp_environmentdictEvent();
  G__cpp_setup_tagtabledictEvent();

  G__cpp_setup_inheritancedictEvent();

  G__cpp_setup_typetabledictEvent();

  G__cpp_setup_memvardictEvent();

  G__cpp_setup_memfuncdictEvent();
  G__cpp_setup_globaldictEvent();
  G__cpp_setup_funcdictEvent();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncdictEvent();
  return;
}
class G__cpp_setup_initdictEvent {
  public:
    G__cpp_setup_initdictEvent() { G__add_setup_func("dictEvent",(G__incsetup)(&G__cpp_setupdictEvent)); G__call_setup_funcs(); }
   ~G__cpp_setup_initdictEvent() { G__remove_setup_func("dictEvent"); }
};
G__cpp_setup_initdictEvent G__cpp_setup_initializerdictEvent;

